set-option -sa terminal-overrides ",xterm*:Tc"

# Set prefix


bind l next-window
bind h previous-window
set -g prefix ^B

set -g history-limit 6942066
set -g renumber-windows on
setw -g mode-keys vi

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-yank'


set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'catppuccin/tmux'


set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application} #{E:@catppuccin_status_session} #[bg=#313244,fg=#cba6f7] 󰥔 #[fg=#cdd6f4]%I:%M %p #[fg=#6c7086]│ #[fg=#a6e3a1]%a #[fg=#cdd6f4]%d %b"


# keybindings
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind r
bind r source ~/.config/tmux/tmux.conf


run "~/.tmux/plugins/tpm/tpm"

